// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: TeslaMateCompanion_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_wifi
void ui_wifi_screen_init(void);
lv_obj_t *ui_wifi;
lv_obj_t *ui_wifi_label;
lv_obj_t *ui_wifi_spinner;
lv_obj_t *ui_wifi_ssid_text;
lv_obj_t *ui_wifi_elapsed_time;


// SCREEN: ui_main
void ui_main_screen_init(void);
lv_obj_t *ui_main;
lv_obj_t *ui_main_car_name;
lv_obj_t *ui_main_elapsed;
lv_obj_t *ui_main_status;
lv_obj_t *ui_main_odometer;
lv_obj_t *ui_main_temp_inside_background;
lv_obj_t *ui_main_temp_inside_label;
lv_obj_t *ui_main_temp_inside_arc;
lv_obj_t *ui_main_temp_inside_value;
lv_obj_t *ui_main_temp_outside_background;
lv_obj_t *ui_main_temp_outside_label;
lv_obj_t *ui_main_temp_outside_arc;
lv_obj_t *ui_main_temp_outside_value;
lv_obj_t *ui_main_healthy_panel;
lv_obj_t *ui_main_healthy_image;
lv_obj_t *ui_main_user_panel;
lv_obj_t *ui_main_user_image;
lv_obj_t *ui_main_sentry_panel;
lv_obj_t *ui_main_sentry_image;
lv_obj_t *ui_main_locked_panel;
lv_obj_t *ui_main_locked_image;
lv_obj_t *ui_main_windows_panel;
lv_obj_t *ui_main_windows_image;
lv_obj_t *ui_main_doors_panel;
lv_obj_t *ui_main_doors_image;
lv_obj_t *ui_main_frunk_panel;
lv_obj_t *ui_main_frunk_image;
lv_obj_t *ui_main_trunk_panel;
lv_obj_t *ui_main_trunk_image;
lv_obj_t *ui_main_battery_bar_panel;
lv_obj_t *ui_main_battery_bar;
lv_obj_t *ui_main_battery_panel;
lv_obj_t *ui_main_battery_value;
lv_obj_t *ui_main_battery_unit_label;
lv_obj_t *ui_main_estimated_panel;
lv_obj_t *ui_main_estimated_label;
lv_obj_t *ui_main_estimated_value;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_wifi_screen_init();
ui_main_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_wifi);
}
