// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: TeslaMateCompanion_Project

#ifndef _TESLAMATECOMPANION_PROJECT_UI_H
#define _TESLAMATECOMPANION_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_wifi
void ui_wifi_screen_init(void);
extern lv_obj_t *ui_wifi;
extern lv_obj_t *ui_wifi_label;
extern lv_obj_t *ui_wifi_spinner;
extern lv_obj_t *ui_wifi_ssid_text;
extern lv_obj_t *ui_wifi_elapsed_time;
// SCREEN: ui_main
void ui_main_screen_init(void);
extern lv_obj_t *ui_main;
extern lv_obj_t *ui_main_car_name;
extern lv_obj_t *ui_main_elapsed;
extern lv_obj_t *ui_main_status;
extern lv_obj_t *ui_main_odometer;
extern lv_obj_t *ui_main_temp_inside_background;
extern lv_obj_t *ui_main_temp_inside_label;
extern lv_obj_t *ui_main_temp_inside_arc;
extern lv_obj_t *ui_main_temp_inside_value;
extern lv_obj_t *ui_main_temp_outside_background;
extern lv_obj_t *ui_main_temp_outside_label;
extern lv_obj_t *ui_main_temp_outside_arc;
extern lv_obj_t *ui_main_temp_outside_value;
extern lv_obj_t *ui_main_healthy_panel;
extern lv_obj_t *ui_main_healthy_image;
extern lv_obj_t *ui_main_user_panel;
extern lv_obj_t *ui_main_user_image;
extern lv_obj_t *ui_main_sentry_panel;
extern lv_obj_t *ui_main_sentry_image;
extern lv_obj_t *ui_main_locked_panel;
extern lv_obj_t *ui_main_locked_image;
extern lv_obj_t *ui_main_windows_panel;
extern lv_obj_t *ui_main_windows_image;
extern lv_obj_t *ui_main_doors_panel;
extern lv_obj_t *ui_main_doors_image;
extern lv_obj_t *ui_main_frunk_panel;
extern lv_obj_t *ui_main_frunk_image;
extern lv_obj_t *ui_main_trunk_panel;
extern lv_obj_t *ui_main_trunk_image;
extern lv_obj_t *ui_main_battery_bar_panel;
extern lv_obj_t *ui_main_battery_bar;
extern lv_obj_t *ui_main_battery_panel;
extern lv_obj_t *ui_main_battery_value;
extern lv_obj_t *ui_main_battery_unit_label;
extern lv_obj_t *ui_main_estimated_panel;
extern lv_obj_t *ui_main_estimated_label;
extern lv_obj_t *ui_main_estimated_value;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_health_png);   // assets/health.png
LV_IMG_DECLARE( ui_img_present_png);   // assets/present.png
LV_IMG_DECLARE( ui_img_sentry_png);   // assets/sentry.png
LV_IMG_DECLARE( ui_img_lock_png);   // assets/lock.png
LV_IMG_DECLARE( ui_img_window_png);   // assets/window.png
LV_IMG_DECLARE( ui_img_doors_png);   // assets/doors.png
LV_IMG_DECLARE( ui_img_frunk_png);   // assets/frunk.png
LV_IMG_DECLARE( ui_img_trunk_png);   // assets/trunk.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
