// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: TeslaMateCompanion_Project

#ifndef _TESLAMATECOMPANION_PROJECT_UI_H
#define _TESLAMATECOMPANION_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_wifi
void ui_wifi_screen_init(void);
extern lv_obj_t *ui_wifi;
extern lv_obj_t *ui_Spinner2;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_ssidtext;
// SCREEN: ui_main
void ui_main_screen_init(void);
extern lv_obj_t *ui_main;
extern lv_obj_t *ui_status;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_pctbar;
extern lv_obj_t *ui_pctnumber;
extern lv_obj_t *ui_kmstotal;
extern lv_obj_t *ui_kmsestimated;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_tempinsidearc;
extern lv_obj_t *ui_tempoutsidearc;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_tempinsidenumber;
extern lv_obj_t *ui_tempoutsidenumber;
extern lv_obj_t *ui_healthpanel;
extern lv_obj_t *ui_imghealth;
extern lv_obj_t *ui_lockedpanel;
extern lv_obj_t *ui_imglock;
extern lv_obj_t *ui_sentrypanel;
extern lv_obj_t *ui_imgsentry;
extern lv_obj_t *ui_userpanel;
extern lv_obj_t *ui_imguser;
extern lv_obj_t *ui_windowspanel;
extern lv_obj_t *ui_imgwindows;
extern lv_obj_t *ui_doorspanel;
extern lv_obj_t *ui_imgdoors;
extern lv_obj_t *ui_frunkpanel;
extern lv_obj_t *ui_imgfrunk;
extern lv_obj_t *ui_trunkpanel;
extern lv_obj_t *ui_imgtrunk;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_health_png);   // assets/health.png
LV_IMG_DECLARE( ui_img_lock_png);   // assets/lock.png
LV_IMG_DECLARE( ui_img_sentry_png);   // assets/sentry.png
LV_IMG_DECLARE( ui_img_present_png);   // assets/present.png
LV_IMG_DECLARE( ui_img_window_png);   // assets/window.png
LV_IMG_DECLARE( ui_img_doors_png);   // assets/doors.png
LV_IMG_DECLARE( ui_img_frunk_png);   // assets/frunk.png
LV_IMG_DECLARE( ui_img_trunk_png);   // assets/trunk.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
