// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: TeslaMateCompanion_Project

#include "ui.h"

void ui_main_screen_init(void)
{
ui_main = lv_obj_create(NULL);
lv_obj_clear_flag( ui_main, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_car_name = lv_label_create(ui_main);
lv_obj_set_width( ui_main_car_name, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_car_name, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_car_name, 6 );
lv_obj_set_y( ui_main_car_name, 1 );
lv_label_set_text(ui_main_car_name,"_");
lv_obj_set_style_text_font(ui_main_car_name, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_elapsed = lv_label_create(ui_main);
lv_obj_set_width( ui_main_elapsed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_elapsed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_elapsed, -6 );
lv_obj_set_y( ui_main_elapsed, 25 );
lv_obj_set_align( ui_main_elapsed, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_main_elapsed,"_");
lv_obj_set_style_text_color(ui_main_elapsed, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_main_elapsed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_main_elapsed, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_status = lv_label_create(ui_main);
lv_obj_set_width( ui_main_status, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_status, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_status, -6 );
lv_obj_set_y( ui_main_status, 1 );
lv_obj_set_align( ui_main_status, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_main_status,"_");
lv_obj_set_style_text_font(ui_main_status, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_odometer = lv_label_create(ui_main);
lv_obj_set_width( ui_main_odometer, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_odometer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_odometer, 7 );
lv_obj_set_y( ui_main_odometer, 25 );
lv_label_set_text(ui_main_odometer,"_");
lv_obj_set_style_text_color(ui_main_odometer, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_main_odometer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_main_odometer, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_temp_inside_background = lv_obj_create(ui_main);
lv_obj_set_width( ui_main_temp_inside_background, 76);
lv_obj_set_height( ui_main_temp_inside_background, 76);
lv_obj_set_x( ui_main_temp_inside_background, -117 );
lv_obj_set_y( ui_main_temp_inside_background, 4 );
lv_obj_set_align( ui_main_temp_inside_background, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_main_temp_inside_background, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_temp_inside_label = lv_label_create(ui_main);
lv_obj_set_width( ui_main_temp_inside_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_temp_inside_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_temp_inside_label, -117 );
lv_obj_set_y( ui_main_temp_inside_label, -25 );
lv_obj_set_align( ui_main_temp_inside_label, LV_ALIGN_CENTER );
lv_label_set_text(ui_main_temp_inside_label,"INTERIOR");
lv_obj_set_style_text_color(ui_main_temp_inside_label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_main_temp_inside_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_main_temp_inside_label, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_temp_inside_arc = lv_arc_create(ui_main);
lv_obj_set_width( ui_main_temp_inside_arc, 60);
lv_obj_set_height( ui_main_temp_inside_arc, 60);
lv_obj_set_x( ui_main_temp_inside_arc, -117 );
lv_obj_set_y( ui_main_temp_inside_arc, 16 );
lv_obj_set_align( ui_main_temp_inside_arc, LV_ALIGN_CENTER );
lv_arc_set_value(ui_main_temp_inside_arc, 0);
lv_obj_set_style_arc_color(ui_main_temp_inside_arc, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_main_temp_inside_arc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_main_temp_inside_arc, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_main_temp_inside_arc, lv_color_hex(0x00B200), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_main_temp_inside_arc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_main_temp_inside_arc, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_main_temp_inside_arc, lv_color_hex(0x00B200), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_main_temp_inside_arc, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_main_temp_inside_arc, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_main_temp_inside_arc, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_main_temp_inside_arc, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_main_temp_inside_arc, -1, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_main_temp_inside_value = lv_label_create(ui_main);
lv_obj_set_width( ui_main_temp_inside_value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_temp_inside_value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_temp_inside_value, -117 );
lv_obj_set_y( ui_main_temp_inside_value, 14 );
lv_obj_set_align( ui_main_temp_inside_value, LV_ALIGN_CENTER );
lv_label_set_text(ui_main_temp_inside_value,"_");
lv_obj_set_style_text_font(ui_main_temp_inside_value, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_temp_outside_background = lv_obj_create(ui_main);
lv_obj_set_width( ui_main_temp_outside_background, 76);
lv_obj_set_height( ui_main_temp_outside_background, 76);
lv_obj_set_x( ui_main_temp_outside_background, -39 );
lv_obj_set_y( ui_main_temp_outside_background, 4 );
lv_obj_set_align( ui_main_temp_outside_background, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_main_temp_outside_background, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_temp_outside_label = lv_label_create(ui_main);
lv_obj_set_width( ui_main_temp_outside_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_temp_outside_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_temp_outside_label, -39 );
lv_obj_set_y( ui_main_temp_outside_label, -25 );
lv_obj_set_align( ui_main_temp_outside_label, LV_ALIGN_CENTER );
lv_label_set_text(ui_main_temp_outside_label,"EXTERIOR");
lv_obj_set_style_text_color(ui_main_temp_outside_label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_main_temp_outside_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_main_temp_outside_label, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_temp_outside_arc = lv_arc_create(ui_main);
lv_obj_set_width( ui_main_temp_outside_arc, 60);
lv_obj_set_height( ui_main_temp_outside_arc, 60);
lv_obj_set_x( ui_main_temp_outside_arc, -39 );
lv_obj_set_y( ui_main_temp_outside_arc, 16 );
lv_obj_set_align( ui_main_temp_outside_arc, LV_ALIGN_CENTER );
lv_arc_set_value(ui_main_temp_outside_arc, 0);
lv_obj_set_style_arc_color(ui_main_temp_outside_arc, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_main_temp_outside_arc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_main_temp_outside_arc, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_main_temp_outside_arc, lv_color_hex(0x00B200), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_main_temp_outside_arc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_main_temp_outside_arc, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_main_temp_outside_arc, lv_color_hex(0x00B200), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_main_temp_outside_arc, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_main_temp_outside_arc, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_main_temp_outside_arc, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_main_temp_outside_arc, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_main_temp_outside_arc, -1, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_main_temp_outside_value = lv_label_create(ui_main);
lv_obj_set_width( ui_main_temp_outside_value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_temp_outside_value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_temp_outside_value, -39 );
lv_obj_set_y( ui_main_temp_outside_value, 14 );
lv_obj_set_align( ui_main_temp_outside_value, LV_ALIGN_CENTER );
lv_label_set_text(ui_main_temp_outside_value,"_");
lv_obj_set_style_text_font(ui_main_temp_outside_value, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_healthy_panel = lv_obj_create(ui_main);
lv_obj_set_width( ui_main_healthy_panel, 37);
lv_obj_set_height( ui_main_healthy_panel, 37);
lv_obj_set_x( ui_main_healthy_panel, -137 );
lv_obj_set_y( ui_main_healthy_panel, 62 );
lv_obj_set_align( ui_main_healthy_panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_main_healthy_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_healthy_image = lv_img_create(ui_main);
lv_img_set_src(ui_main_healthy_image, &ui_img_health_png);
lv_obj_set_width( ui_main_healthy_image, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_healthy_image, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_healthy_image, -137 );
lv_obj_set_y( ui_main_healthy_image, 62 );
lv_obj_set_align( ui_main_healthy_image, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_main_healthy_image, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_main_healthy_image, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_main_healthy_image,170);
lv_obj_set_style_img_recolor(ui_main_healthy_image, lv_color_hex(0x000000), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_main_healthy_image, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_user_panel = lv_obj_create(ui_main);
lv_obj_set_width( ui_main_user_panel, 37);
lv_obj_set_height( ui_main_user_panel, 37);
lv_obj_set_x( ui_main_user_panel, -98 );
lv_obj_set_y( ui_main_user_panel, 62 );
lv_obj_set_align( ui_main_user_panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_main_user_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_user_image = lv_img_create(ui_main);
lv_img_set_src(ui_main_user_image, &ui_img_present_png);
lv_obj_set_width( ui_main_user_image, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_user_image, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_user_image, -98 );
lv_obj_set_y( ui_main_user_image, 62 );
lv_obj_set_align( ui_main_user_image, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_main_user_image, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_main_user_image, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_main_user_image,170);
lv_obj_set_style_img_recolor(ui_main_user_image, lv_color_hex(0x000000), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_main_user_image, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_sentry_panel = lv_obj_create(ui_main);
lv_obj_set_width( ui_main_sentry_panel, 37);
lv_obj_set_height( ui_main_sentry_panel, 37);
lv_obj_set_x( ui_main_sentry_panel, -59 );
lv_obj_set_y( ui_main_sentry_panel, 62 );
lv_obj_set_align( ui_main_sentry_panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_main_sentry_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_sentry_image = lv_img_create(ui_main);
lv_img_set_src(ui_main_sentry_image, &ui_img_sentry_png);
lv_obj_set_width( ui_main_sentry_image, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_sentry_image, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_sentry_image, -59 );
lv_obj_set_y( ui_main_sentry_image, 62 );
lv_obj_set_align( ui_main_sentry_image, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_main_sentry_image, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_main_sentry_image, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_main_sentry_image,170);
lv_obj_set_style_img_recolor(ui_main_sentry_image, lv_color_hex(0x000000), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_main_sentry_image, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_locked_panel = lv_obj_create(ui_main);
lv_obj_set_width( ui_main_locked_panel, 37);
lv_obj_set_height( ui_main_locked_panel, 37);
lv_obj_set_x( ui_main_locked_panel, -20 );
lv_obj_set_y( ui_main_locked_panel, 62 );
lv_obj_set_align( ui_main_locked_panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_main_locked_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_locked_image = lv_img_create(ui_main);
lv_img_set_src(ui_main_locked_image, &ui_img_lock_png);
lv_obj_set_width( ui_main_locked_image, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_locked_image, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_locked_image, -20 );
lv_obj_set_y( ui_main_locked_image, 61 );
lv_obj_set_align( ui_main_locked_image, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_main_locked_image, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_main_locked_image, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_main_locked_image,170);
lv_obj_set_style_img_recolor(ui_main_locked_image, lv_color_hex(0x000000), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_main_locked_image, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_windows_panel = lv_obj_create(ui_main);
lv_obj_set_width( ui_main_windows_panel, 37);
lv_obj_set_height( ui_main_windows_panel, 37);
lv_obj_set_x( ui_main_windows_panel, 19 );
lv_obj_set_y( ui_main_windows_panel, 62 );
lv_obj_set_align( ui_main_windows_panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_main_windows_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_windows_image = lv_img_create(ui_main);
lv_img_set_src(ui_main_windows_image, &ui_img_window_png);
lv_obj_set_width( ui_main_windows_image, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_windows_image, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_windows_image, 19 );
lv_obj_set_y( ui_main_windows_image, 61 );
lv_obj_set_align( ui_main_windows_image, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_main_windows_image, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_main_windows_image, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_main_windows_image,170);
lv_obj_set_style_img_recolor(ui_main_windows_image, lv_color_hex(0x000000), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_main_windows_image, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_doors_panel = lv_obj_create(ui_main);
lv_obj_set_width( ui_main_doors_panel, 37);
lv_obj_set_height( ui_main_doors_panel, 37);
lv_obj_set_x( ui_main_doors_panel, 58 );
lv_obj_set_y( ui_main_doors_panel, 62 );
lv_obj_set_align( ui_main_doors_panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_main_doors_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_doors_image = lv_img_create(ui_main);
lv_img_set_src(ui_main_doors_image, &ui_img_doors_png);
lv_obj_set_width( ui_main_doors_image, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_doors_image, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_doors_image, 57 );
lv_obj_set_y( ui_main_doors_image, 61 );
lv_obj_set_align( ui_main_doors_image, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_main_doors_image, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_main_doors_image, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_main_doors_image,170);
lv_obj_set_style_img_recolor(ui_main_doors_image, lv_color_hex(0x000000), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_main_doors_image, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_frunk_panel = lv_obj_create(ui_main);
lv_obj_set_width( ui_main_frunk_panel, 37);
lv_obj_set_height( ui_main_frunk_panel, 37);
lv_obj_set_x( ui_main_frunk_panel, 97 );
lv_obj_set_y( ui_main_frunk_panel, 62 );
lv_obj_set_align( ui_main_frunk_panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_main_frunk_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_frunk_image = lv_img_create(ui_main);
lv_img_set_src(ui_main_frunk_image, &ui_img_frunk_png);
lv_obj_set_width( ui_main_frunk_image, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_frunk_image, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_frunk_image, 97 );
lv_obj_set_y( ui_main_frunk_image, 61 );
lv_obj_set_align( ui_main_frunk_image, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_main_frunk_image, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_main_frunk_image, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_main_frunk_image,170);
lv_obj_set_style_img_recolor(ui_main_frunk_image, lv_color_hex(0x000000), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_main_frunk_image, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_trunk_panel = lv_obj_create(ui_main);
lv_obj_set_width( ui_main_trunk_panel, 37);
lv_obj_set_height( ui_main_trunk_panel, 37);
lv_obj_set_x( ui_main_trunk_panel, 136 );
lv_obj_set_y( ui_main_trunk_panel, 62 );
lv_obj_set_align( ui_main_trunk_panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_main_trunk_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_trunk_image = lv_img_create(ui_main);
lv_img_set_src(ui_main_trunk_image, &ui_img_trunk_png);
lv_obj_set_width( ui_main_trunk_image, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_trunk_image, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_trunk_image, 136 );
lv_obj_set_y( ui_main_trunk_image, 62 );
lv_obj_set_align( ui_main_trunk_image, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_main_trunk_image, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_main_trunk_image, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_main_trunk_image,170);
lv_obj_set_style_img_recolor(ui_main_trunk_image, lv_color_hex(0x000000), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_main_trunk_image, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_battery_bar_panel = lv_obj_create(ui_main);
lv_obj_set_width( ui_main_battery_bar_panel, 48);
lv_obj_set_height( ui_main_battery_bar_panel, 37);
lv_obj_set_x( ui_main_battery_bar_panel, 25 );
lv_obj_set_y( ui_main_battery_bar_panel, -16 );
lv_obj_set_align( ui_main_battery_bar_panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_main_battery_bar_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_battery_bar = lv_bar_create(ui_main);
lv_obj_set_width( ui_main_battery_bar, 16);
lv_obj_set_height( ui_main_battery_bar, 27);
lv_obj_set_x( ui_main_battery_bar, 22 );
lv_obj_set_y( ui_main_battery_bar, -16 );
lv_obj_set_align( ui_main_battery_bar, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_main_battery_bar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_main_battery_bar, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_main_battery_bar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_main_battery_bar, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_main_battery_bar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_main_battery_bar, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_main_battery_bar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_main_battery_bar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_main_battery_bar, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_main_battery_bar, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_main_battery_bar, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_main_battery_bar, lv_color_hex(0x00B200), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_main_battery_bar, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_main_battery_panel = lv_obj_create(ui_main);
lv_obj_set_width( ui_main_battery_panel, 115);
lv_obj_set_height( ui_main_battery_panel, 37);
lv_obj_set_x( ui_main_battery_panel, 97 );
lv_obj_set_y( ui_main_battery_panel, -16 );
lv_obj_set_align( ui_main_battery_panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_main_battery_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_battery_value = lv_label_create(ui_main);
lv_obj_set_width( ui_main_battery_value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_battery_value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_battery_value, -38 );
lv_obj_set_y( ui_main_battery_value, 48 );
lv_obj_set_align( ui_main_battery_value, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_main_battery_value,"_");
lv_obj_set_style_text_font(ui_main_battery_value, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_battery_unit_label = lv_label_create(ui_main);
lv_obj_set_width( ui_main_battery_unit_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_battery_unit_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_battery_unit_label, -12 );
lv_obj_set_y( ui_main_battery_unit_label, 59 );
lv_obj_set_align( ui_main_battery_unit_label, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_main_battery_unit_label,"%");
lv_obj_set_style_text_font(ui_main_battery_unit_label, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_estimated_panel = lv_obj_create(ui_main);
lv_obj_set_width( ui_main_estimated_panel, 154);
lv_obj_set_height( ui_main_estimated_panel, 37);
lv_obj_set_x( ui_main_estimated_panel, 78 );
lv_obj_set_y( ui_main_estimated_panel, 23 );
lv_obj_set_align( ui_main_estimated_panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_main_estimated_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_estimated_label = lv_label_create(ui_main);
lv_obj_set_width( ui_main_estimated_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_estimated_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_estimated_label, 167 );
lv_obj_set_y( ui_main_estimated_label, 98 );
lv_label_set_text(ui_main_estimated_label,"Est.");
lv_obj_set_style_text_color(ui_main_estimated_label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_main_estimated_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_main_estimated_label, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_estimated_value = lv_label_create(ui_main);
lv_obj_set_width( ui_main_estimated_value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_estimated_value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_estimated_value, -12 );
lv_obj_set_y( ui_main_estimated_value, 96 );
lv_obj_set_align( ui_main_estimated_value, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_main_estimated_value,"_");
lv_obj_set_style_text_font(ui_main_estimated_value, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_update_spinner = lv_spinner_create(ui_main,1000,90);
lv_obj_set_width( ui_main_update_spinner, 18);
lv_obj_set_height( ui_main_update_spinner, 18);
lv_obj_set_x( ui_main_update_spinner, 144 );
lv_obj_set_y( ui_main_update_spinner, -48 );
lv_obj_set_align( ui_main_update_spinner, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_main_update_spinner, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_opa(ui_main_update_spinner, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_main_update_spinner, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_main_update_spinner, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_main_update_spinner, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_main_update_spinner, lv_color_hex(0xFF8200), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_main_update_spinner, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_main_update_spinner, 3, LV_PART_INDICATOR| LV_STATE_DEFAULT);

}
