// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: TeslaMateCompanion_Project

#include "ui.h"

void ui_wifi_screen_init(void)
{
ui_wifi = lv_obj_create(NULL);
lv_obj_clear_flag( ui_wifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Spinner2 = lv_spinner_create(ui_wifi,1000,90);
lv_obj_set_width( ui_Spinner2, 80);
lv_obj_set_height( ui_Spinner2, 80);
lv_obj_set_x( ui_Spinner2, 0 );
lv_obj_set_y( ui_Spinner2, -9 );
lv_obj_set_align( ui_Spinner2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner2, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_Label13 = lv_label_create(ui_wifi);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label13, 0 );
lv_obj_set_y( ui_Label13, -66 );
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"Connexion wifi en cours...");
lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label14 = lv_label_create(ui_wifi);
lv_obj_set_width( ui_Label14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label14, 1 );
lv_obj_set_y( ui_Label14, 44 );
lv_obj_set_align( ui_Label14, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label14,"SSID");

ui_ssidtext = lv_label_create(ui_wifi);
lv_obj_set_width( ui_ssidtext, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ssidtext, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ssidtext, 0 );
lv_obj_set_y( ui_ssidtext, 66 );
lv_obj_set_align( ui_ssidtext, LV_ALIGN_CENTER );
lv_label_set_text(ui_ssidtext,"XXXXXXXXXXXXXX");
lv_obj_set_style_text_font(ui_ssidtext, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

}
